<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="Administrators_EmailViewer_Default" Title="RankTrend.com - Email Viewer" %>
<asp:Content ID="Content1" ContentPlaceHolderID="mainContent" Runat="Server">
	<h3>Unsent Emails:</h3>
	<ajax:AjaxPanel ID="AjaxPanel1" runat="server">
        <asp:SqlDataSource runat="server" ID="UnsentEmailSource" ConnectionString="<%$ ConnectionStrings:main %>"
            SelectCommand="Email_GetUnsentEmails" SelectCommandType="StoredProcedure" DeleteCommand="Delete From EmailQueue Where Id=@Id">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="int32" />
            </DeleteParameters>
        </asp:SqlDataSource>
        <asp:GridView runat="server" ID="MyGridView" DataSourceID="UnsentEmailSource" CssClass="DataGridView EmailQueue"
            DataKeyNames="Id" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" CellPadding="3">
						<RowStyle VerticalAlign="top" />
            <Columns>
							<asp:TemplateField HeaderText="Message" ItemStyle-CssClass="LeftAlign">
								<ItemTemplate>
									<div class="EmailQueueHeader">
										<table cellpadding="0" cellspacing="0">
											<tr>
												<th>Subject:</th>
												<td><b><%# DataBinder.Eval(Container.DataItem, "Subject") %></b></td>
											</tr>
											<tr>
												<th>From:</th>
												<td><%# DataBinder.Eval(Container.DataItem, "From") %></td>
											</tr>
											<tr>
												<th>Date:</th>
												<td><%# DataBinder.Eval(Container.DataItem, "QueuedOn") %></td>
											</tr>
											<tr>
												<th>To:</th>
												<td><a href="mailto:<%# DataBinder.Eval(Container.DataItem, "ToName") != DBNull.Value ? "'" + DataBinder.Eval(Container.DataItem, "ToName") + "' " : string.Empty %> <<%# DataBinder.Eval(Container.DataItem, "ToAddress") %>>"><%# DataBinder.Eval(Container.DataItem, "ToName") != DBNull.Value ? "'" + DataBinder.Eval(Container.DataItem, "ToName") + "' " : string.Empty %>&lt;<%# DataBinder.Eval(Container.DataItem, "ToAddress") %>&gt;</a></td>
											</tr>
											<tr>
												<th>Tries:</th>
												<td><%# DataBinder.Eval(Container.DataItem, "NumberOfTries") %></td>
											</tr>
											<tr>
												<th>Last Try:</th>
												<td><%# DataBinder.Eval(Container.DataItem, "LastTry") %></td>
											</tr>
										</table>
									</div>
									<div class="EmailBody">
										<%# GetMessage((string)DataBinder.Eval(Container.DataItem, "Message"), (bool)DataBinder.Eval(Container.DataItem, "Html")) %>
									</div>
								</ItemTemplate>
							</asp:TemplateField>
            </Columns>
        </asp:GridView>
    </ajax:AjaxPanel>
</asp:Content>

