//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace Rt.TrayApplication.Webservices {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrayApplicationSoap", Namespace="http://www.RankTrend.com/TrayAppplication")]
    public partial class TrayApplication : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMinimumClientVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecordErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueueNextDatasourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDatasourceRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveDatasourceResponseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrayApplication() {
            this.Url = global::Rt.TrayApplication.Properties.Settings.Default.Rt_TrayApplication_Rt_Webservices_TrayApplication;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMinimumClientVersionCompletedEventHandler GetMinimumClientVersionCompleted;
        
        /// <remarks/>
        public event AuthenticateCompletedEventHandler AuthenticateCompleted;
        
        /// <remarks/>
        public event RecordErrorCompletedEventHandler RecordErrorCompleted;
        
        /// <remarks/>
        public event QueueNextDatasourceCompletedEventHandler QueueNextDatasourceCompleted;
        
        /// <remarks/>
        public event GetDatasourceRequestCompletedEventHandler GetDatasourceRequestCompleted;
        
        /// <remarks/>
        public event SaveDatasourceResponseCompletedEventHandler SaveDatasourceResponseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.RankTrend.com/TrayAppplication/GetMinimumClientVersion", RequestNamespace="http://www.RankTrend.com/TrayAppplication", ResponseNamespace="http://www.RankTrend.com/TrayAppplication", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMinimumClientVersion() {
            object[] results = this.Invoke("GetMinimumClientVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMinimumClientVersionAsync() {
            this.GetMinimumClientVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetMinimumClientVersionAsync(object userState) {
            if ((this.GetMinimumClientVersionOperationCompleted == null)) {
                this.GetMinimumClientVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMinimumClientVersionOperationCompleted);
            }
            this.InvokeAsync("GetMinimumClientVersion", new object[0], this.GetMinimumClientVersionOperationCompleted, userState);
        }
        
        private void OnGetMinimumClientVersionOperationCompleted(object arg) {
            if ((this.GetMinimumClientVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMinimumClientVersionCompleted(this, new GetMinimumClientVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.RankTrend.com/TrayAppplication/Authenticate", RequestNamespace="http://www.RankTrend.com/TrayAppplication", ResponseNamespace="http://www.RankTrend.com/TrayAppplication", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Authenticate(string userName, string password) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        userName,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string userName, string password) {
            this.AuthenticateAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string userName, string password, object userState) {
            if ((this.AuthenticateOperationCompleted == null)) {
                this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("Authenticate", new object[] {
                        userName,
                        password}, this.AuthenticateOperationCompleted, userState);
        }
        
        private void OnAuthenticateOperationCompleted(object arg) {
            if ((this.AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.RankTrend.com/TrayAppplication/RecordError", RequestNamespace="http://www.RankTrend.com/TrayAppplication", ResponseNamespace="http://www.RankTrend.com/TrayAppplication", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RecordError(string guid, string exceptionString) {
            this.Invoke("RecordError", new object[] {
                        guid,
                        exceptionString});
        }
        
        /// <remarks/>
        public void RecordErrorAsync(string guid, string exceptionString) {
            this.RecordErrorAsync(guid, exceptionString, null);
        }
        
        /// <remarks/>
        public void RecordErrorAsync(string guid, string exceptionString, object userState) {
            if ((this.RecordErrorOperationCompleted == null)) {
                this.RecordErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecordErrorOperationCompleted);
            }
            this.InvokeAsync("RecordError", new object[] {
                        guid,
                        exceptionString}, this.RecordErrorOperationCompleted, userState);
        }
        
        private void OnRecordErrorOperationCompleted(object arg) {
            if ((this.RecordErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecordErrorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.RankTrend.com/TrayAppplication/QueueNextDatasource", RequestNamespace="http://www.RankTrend.com/TrayAppplication", ResponseNamespace="http://www.RankTrend.com/TrayAppplication", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueueNextDatasource(string guidString) {
            object[] results = this.Invoke("QueueNextDatasource", new object[] {
                        guidString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueueNextDatasourceAsync(string guidString) {
            this.QueueNextDatasourceAsync(guidString, null);
        }
        
        /// <remarks/>
        public void QueueNextDatasourceAsync(string guidString, object userState) {
            if ((this.QueueNextDatasourceOperationCompleted == null)) {
                this.QueueNextDatasourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueueNextDatasourceOperationCompleted);
            }
            this.InvokeAsync("QueueNextDatasource", new object[] {
                        guidString}, this.QueueNextDatasourceOperationCompleted, userState);
        }
        
        private void OnQueueNextDatasourceOperationCompleted(object arg) {
            if ((this.QueueNextDatasourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueueNextDatasourceCompleted(this, new QueueNextDatasourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.RankTrend.com/TrayAppplication/GetDatasourceRequest", RequestNamespace="http://www.RankTrend.com/TrayAppplication", ResponseNamespace="http://www.RankTrend.com/TrayAppplication", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializableWebRequest GetDatasourceRequest(string requestKey) {
            object[] results = this.Invoke("GetDatasourceRequest", new object[] {
                        requestKey});
            return ((SerializableWebRequest)(results[0]));
        }
        
        /// <remarks/>
        public void GetDatasourceRequestAsync(string requestKey) {
            this.GetDatasourceRequestAsync(requestKey, null);
        }
        
        /// <remarks/>
        public void GetDatasourceRequestAsync(string requestKey, object userState) {
            if ((this.GetDatasourceRequestOperationCompleted == null)) {
                this.GetDatasourceRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatasourceRequestOperationCompleted);
            }
            this.InvokeAsync("GetDatasourceRequest", new object[] {
                        requestKey}, this.GetDatasourceRequestOperationCompleted, userState);
        }
        
        private void OnGetDatasourceRequestOperationCompleted(object arg) {
            if ((this.GetDatasourceRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatasourceRequestCompleted(this, new GetDatasourceRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.RankTrend.com/TrayAppplication/SaveDatasourceResponse", RequestNamespace="http://www.RankTrend.com/TrayAppplication", ResponseNamespace="http://www.RankTrend.com/TrayAppplication", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveDatasourceResponse(SerializableWebResponse response, string requestKey) {
            this.Invoke("SaveDatasourceResponse", new object[] {
                        response,
                        requestKey});
        }
        
        /// <remarks/>
        public void SaveDatasourceResponseAsync(SerializableWebResponse response, string requestKey) {
            this.SaveDatasourceResponseAsync(response, requestKey, null);
        }
        
        /// <remarks/>
        public void SaveDatasourceResponseAsync(SerializableWebResponse response, string requestKey, object userState) {
            if ((this.SaveDatasourceResponseOperationCompleted == null)) {
                this.SaveDatasourceResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveDatasourceResponseOperationCompleted);
            }
            this.InvokeAsync("SaveDatasourceResponse", new object[] {
                        response,
                        requestKey}, this.SaveDatasourceResponseOperationCompleted, userState);
        }
        
        private void OnSaveDatasourceResponseOperationCompleted(object arg) {
            if ((this.SaveDatasourceResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveDatasourceResponseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.RankTrend.com/TrayAppplication")]
    public partial class SerializableWebRequest {
        
        private string urlField;
        
        private string postDataField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string PostData {
            get {
                return this.postDataField;
            }
            set {
                this.postDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.RankTrend.com/TrayAppplication")]
    public partial class SerializableWebResponse {
        
        private string contentField;
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetMinimumClientVersionCompletedEventHandler(object sender, GetMinimumClientVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMinimumClientVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMinimumClientVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void RecordErrorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void QueueNextDatasourceCompletedEventHandler(object sender, QueueNextDatasourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueueNextDatasourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueueNextDatasourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetDatasourceRequestCompletedEventHandler(object sender, GetDatasourceRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatasourceRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatasourceRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializableWebRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializableWebRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SaveDatasourceResponseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591